# Generated by Django 5.0.2 on 2024-03-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neutral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('menu_category', models.CharField(max_length=20)),
            ],
        ),
    ]
