# Generated by Django 5.0.2 on 2024-05-31 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0003_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Neutral',
        ),
        migrations.DeleteModel(
            name='Non_veg_item',
        ),
        migrations.DeleteModel(
            name='Veg_item',
        ),
    ]
