# Generated by Django 5.0.2 on 2024-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0007_orders_alter_orderitem_order_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
