# Generated by Django 5.0.2 on 2024-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0008_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
